import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import Todo from "./components/Todo/Todo";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-2">
          <Navbar /> <br />

          <main className="w-full flex ">
            <section className="w-3/5">{children}</section>
            <section className="w-2/5 p-0">
              
              <Todo />
            </section>
          </main>
        </div>
      </body>
    </html>
  );
}
