import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import Todo from "./components/ToDo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />

        <main className="w-full mx-auto flex mt-2">
          <section className="w-2/3">{children}</section>
          <section className="w-1/3">
            <Todo />
          </section>
        </main>
      </body>
    </html>
  );
}
